### ISSUE TITLE
GFX Library version issue

### ISSUE THREAD

**Issue by gromain** [CoretechR/Keybon#4]
Hey,

I have a failure to build if we are using a recent release of the GFX Library.

I manage to build properly with v1.7.5.

The new releases of this library introduced changes in the files for MonoOLED (later renamed to GreyOLED) that include `I2CDevices.h`.
This inclusion leads to a weird error:
`Adafruit_I2CDevice.cpp:88:47: error: invalid conversion from 'const uint8_t* {aka const unsigned char*}' to 'uint8* {aka unsigned char*}' [-fpermissive]`

Anyway, it builds fine with v1.7.5. I recommend putting a comment in the code regarding the version or in the documentation somewhere!

**Comment by gromain** [comment]
Also, I just saw that this is indeed written in the README.

I should have read better. Closing now.

PS: Here is the comment I added to my code to make it compile: https://github.com/gromain/Keybon/blob/c42e671557db5b1d7b2e6edbb2c09094952361df/keybon/keybon.ino#L4

**Comment by rpavlik** [comment]
Did this issue get reported upstream so that it can be fixed?

**Comment by gromain** [comment]
I didn't, not sure if @CoretechR did it!

**Comment by CoretechR** [comment]
I did not report it either. I thought there was an issue in the Adafruit repo already but couldn't find it.
